package com.modcmga.backendservice.model.enums;
/**
 * @Package: com.modcmga.backendservice.model.enums
 * @Class: FitnessFunctionType
 * @Author: Jan
 * @Date: 18.05.2022
 */

/**
 * The type to denote
 */
public enum ObjectiveType {
    BALANCEDNESS,
    MAXIMISE_COHESION,
    MAXIMISE_AVG_COHESION,
    MAXIMISE_MEDIAN_COHESION,
    MINIMISE_COUPLING,
    OPTIMAL_SIZED_MODULE,
    OPTIMAL_NUMBER_OF_MODULES,
    MEDIAN_CLOSENESS_CENTRALITY_PER_MODULE,
    AVERAGE_EDGE_BETWEENNESS_CENTRALITY_PER_MODULE,
    AVERAGE_CLOSENESS_CENTRALITY_PER_MODULE,

    MAX_AVG_STRING_SIMILARITY_PER_MODULE,

    MAX_STRING_DIFFERENCE_BETWEEN_MODULES,
    MAX_STRING_SEMANTIC_SIMILARITY_WITHIN_MODULES_OBJECTIVE,
    MAX_STRING_SEMANTIC_DIFFERENCE_BETWEEN_MODULES_OBJECTIVE,
    MIN_SMELLS,
    MAX_MODULARITY
}
